services:

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306'