spring:

  jpa:
    properties:
      hibernate:
        show_sql: false     # Log SQL statements
        format_sql: false   # Format SQL output in logs

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000

  flyway:
    enabled: false

  docker:
    compose:
      enabled: false