apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-mvc
  strategy: {}
  template:
    metadata:
      labels:
        app: rest-mvc
    spec:
      containers:
      - image: spring-7-rest-mvc:0.0.1-SNAPSHOT
        name: spring-7-rest-mvc
        resources: {}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: local-mysql
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: http://auth-server:9000
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: restadmin
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SERVER_PORT
          value: "8080"
status: {}
