classDiagram
 class Customer {
  UUID id
  Integer version
  String name
  String email
  Instant createdAt
  Instant updatedAt
 }

 class MilkOrder {
  UUID id
  Integer version
  String customerRef
  BigDecimal paymentAmount
  Instant createdAt
  Instant updatedAt
  addOrderLine(OrderLine)
  removeOrderLine(OrderLine)
  addOrderShipment(OrderShipment)
  getTotalAmount() BigDecimal
 }

 class OrderLine {
  UUID id
  Integer requestedQuantity
  Integer assignedQuantity
  BigDecimal priceAtPurchase
  OrderLineStatus orderLineStatus
  createLine(Milk milk, Integer quantity)$ OrderLine
 }

 class OrderLineStatus {
  <<enumeration>>
  NEW
  COMPLETE
 }

 class OrderShipment {
  UUID id
  String trackingNumber
  Instant createdAt
  Instant updatedAt
 }

 class Milk {
  UUID id
  String name
  MilkType milkType
  String upc
  BigDecimal price
  Integer stock
  Instant createdAt
  Instant updatedAt
  addCategory(Category category)
 }

 class MilkType {
  <<enumeration>>
  A2
  GOAT
  HIGH_PROTEIN
  LACTOSE_FREE
  ORGANIC_WHOLE
  SEMI_SKIMMED
  SKIMMED
  WHOLE
 }

 class Category {
  UUID id
  String description
  Instant createdAt
  Instant updatedAt
 }

 Customer "1" -- "0..*" MilkOrder : places
 MilkOrder "1" *-- "1..*" OrderLine : contains
 MilkOrder "1" -- "0..1" OrderShipment : tracking
 OrderLine "n" -- "1" Milk : references
 OrderLine -- OrderLineStatus : status
 Milk "n" -- "m" Category : belongs to
 Milk -- MilkType : type